# Generated by Django 5.0.6 on 2024-07-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='binance_id',
            field=models.CharField(default=1234, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
